general {
    lock_cmd = pidof hyprlock || hyprlock # runs hyprlock if it is not already running (this is always run when "loginctl lock-session" is called)
    # unlock_cmd = killall hyprlock # kills hyprlock when unlocking (this is always run when "loginctl unlock-session" is called)
    before_sleep_cmd = loginctl lock-session # ensures that the session is locked before going to sleep
    # on_lock_cmd = sleep 10 && systemctl suspend
}

# Decrease brightnessn off screen faster if session is already locked
listener {
    timeout = 240 # 4 min
    on-timeout = brightnessctl -s set 1
    on-resume = brightnessctl -r
}

# Screenlock
listener {
    timeout = 300 # 5 min
    on-timeout = loginctl lock-session
}

# Suspend
listener {
    timeout = 310 # right after 10 sec
    on-timeout = systemctl suspend
}
